
// ALL CAMPUSES
export const REQUEST_CAMPUSES = 'REQUEST_CAMPUSES'
export const RECEIVE_CAMPUSES = 'RECEIVE_CAMPUSES'

// ALL STUDENTS
export const REQUEST_STUDENTS = 'REQUEST_STUDENTS'
export const RECEIVE_STUDENTS = 'RECEIVE_STUDENTS'

// SINGLE CAMPUS
export const CREATE_CAMPUS = 'CREATE_CAMPUS'
export const REQUEST_CAMPUS = 'REQUEST_CAMPUS'
export const RECEIVE_CAMPUS = 'RECEIVE_CAMPUS'
export const RECEIVE_UPDATED_STUDENTS_AND_CAMPUS = 'RECEIVE_UPDATED_STUDENTS_AND_CAMPUS'
export const UPDATE_CAMPUS = 'UPDATE_CAMPUS'
export const DELETE_CAMPUS = 'DELETE_CAMPUS'

// SINGLE STUDENT
export const CREATE_STUDENT = 'CREATE_STUDENT'
export const REQUEST_STUDENT = 'REQUEST_STUDENT'
export const UPDATE_STUDENT = 'UPDATE_STUDENT'
export const DELETE_STUDENT = 'DELETE_STUDENT'
