// ALL CAMPUSES
export const UPDATE_CAMPUSES = 'UPDATE_CAMPUSES'

// ALL STUDENTS
export const UPDATE_STUDENTS = 'UPDATE_STUDENTS'

// SINGLE CAMPUS
export const UPDATE_CAMPUS = 'UPDATE_CAMPUS'

// SINGLE STUDENT
export const UPDATE_STUDENT = 'UPDATE_STUDENT'
